/**
 * The site's mark, generated by the library it advertises.
 *
 * Not a hand-drawn asset: this is literally `blobatar("alain00")` with no
 * options — the same call the hero makes on load, so the tab icon and the first
 * thing you see on the page cannot drift apart. Regenerated on every build and
 * every dev boot, so if the library's shapes or palette ever change, the favicon
 * changes with them instead of quietly becoming a picture of an older version.
 */
import { blobatar } from "blobatar";

/**
 * A blobatar leaves ~15% margin inside its 100×100 box — right for an avatar
 * sitting in a layout, wasteful for a 16px tab icon where every pixel of the
 * mark counts. Cropping the viewBox scales the body up without touching the
 * geometry.
 *
 * Stated as an inset rather than seed-specific bounds on purpose. The library
 * centers a body in its box by construction, so this holds for any seed; a
 * literal bounding box read off this one blobatar's path data would be a
 * constant that silently stops being true.
 */
const INSET = 11.5;

export const FAVICON = blobatar("alain00").replace(
  'viewBox="0 0 100 100"',
  `viewBox="${INSET} ${INSET} ${100 - INSET * 2} ${100 - INSET * 2}"`,
);

/** Where the generated documents expect to find it, relative to this directory. */
export const FAVICON_PATH = new URL("./favicon.svg", import.meta.url).pathname;

/**
 * Materializes the mark on disk.
 *
 * A document has to reference the icon through a normal `<link href>`, and
 * Bun's HTML bundler resolves that href against the filesystem — an absolute
 * URL is a build error rather than a passthrough, which is why the trick the
 * fonts use (inline `<style>`, absolute `/fonts/...`) does not transfer here.
 * So the generated file is written out before anything reads the HTML, by both
 * the build and the dev server. It is gitignored: the source of truth is the
 * call above, not the bytes.
 */
export async function writeFavicon() {
  await Bun.write(FAVICON_PATH, FAVICON);
}
