/**
 * 邮票经典模板定义（Templates）
 * 包含 Beacon、National park、Wildlife、Maritime、Botanical、Engineering 6 款预设
 */

import type { StampStudioSettings } from './types';

export interface StampTemplate {
  id: string;
  label: string;
  description: string;
  themeColor: string;
  settings: Partial<StampStudioSettings>;
}

/** 默认未启用高级特性的极简原图工坊设置 */
export const defaultStudioSettings: StampStudioSettings = {
  print: 'offset',
  inkColor: '#1d3f6e',
  ink: 1,
  relief: 0.35,

  designOn: false,
  frame: 'classic',
  frameColor: '#1d3f6e',
  margin: 0.065,
  ornament: 'none',
  ornamentSize: 0.1,
  vignette: 'none',
  vignetteRule: true,
  vignetteColor: '#1d3f6e',
  feather: 0,
  artFit: 'cover',

  country: '中国邮政 CHINA',
  countryArc: false,
  denomination: '¥1.20',
  denomAnchor: 'bottom-left',
  tablets: false,
  caption: '',
  ribbon: false,
  typeface: 'serif',

  ground: 'none',
  groundColor: '#1d3f6e',
  groundWeight: 0.4,
  groundScale: 0.35,
  groundAngle: 0.125,
  groundStrength: 0.5,
  groundUnderArt: false,
  groundClear: 0.5,

  toning: 0.1,
  fiber: 0.3,
  foxing: 0.05,
  wear: 0.08,

  edge: 'perforated',
  gauge: 11.5,
  holeSize: 0.3,
  tear: 0.2,

  postmarkOn: false,
  postmarkStyle: 'both',
  postmarkColor: '#1c1b1f',
  postmarkCity: 'BEIJING',
  postmarkSubtext: '中国邮政',
  postmarkDate: '2024.10.01',
  postmarkAngle: 11,
  postmarkPos: { x: 0.35, y: 0.62 },
  postmarkStrength: 0.55,
};

/** 6 大经典邮票工坊模板 */
export const STAMP_TEMPLATES: StampTemplate[] = [
  {
    id: 'beacon',
    label: 'Beacon 灯塔',
    description: '深邃蓝调雕刻版 · 拱形视窗与机雕防伪底纹',
    themeColor: '#14418c',
    settings: {
      designOn: true,
      print: 'engraved',
      inkColor: '#14418c',
      frameColor: '#14418c',
      vignetteColor: '#14418c',
      frame: 'arched',
      vignette: 'arch',
      vignetteRule: true,
      countryArc: true,
      tablets: true,
      ribbon: false,
      country: 'CHINA POST 中国邮政',
      denomination: '20',
      caption: '',
      ground: 'guilloche',
      groundColor: '#14418c',
      groundWeight: 0.55,
      groundScale: 0.5,
      groundStrength: 0.48,
      margin: 0.055,
      gauge: 11,
      toning: 0.25,
      wear: 0.15,
      foxing: 0.08,
      edge: 'perforated',
    },
  },
  {
    id: 'national-park',
    label: 'National Park 国家公园',
    description: '旷野翠绿雕版 · 边缘羽化与副题复古飘带',
    themeColor: '#1f5c3a',
    settings: {
      designOn: true,
      print: 'engraved',
      inkColor: '#1f5c3a',
      frameColor: '#1f5c3a',
      vignetteColor: '#1f5c3a',
      frame: 'classic',
      vignette: 'rect',
      vignetteRule: false,
      feather: 0.38,
      ribbon: true,
      tablets: false,
      countryArc: false,
      country: 'NATIONAL PARKS 自然保护',
      denomination: '15',
      caption: 'ROCKY MOUNTAIN',
      ground: 'burelage',
      groundColor: '#1f5c3a',
      groundWeight: 0.35,
      groundScale: 0.4,
      groundAngle: 0.38,
      groundStrength: 0.12,
      groundUnderArt: true,
      margin: 0.05,
      toning: 0.2,
      edge: 'perforated',
    },
  },
  {
    id: 'wildlife',
    label: 'Wildlife 飞鸟生灵',
    description: '水青色照相凹版 · 华丽滚珠边框与莨苕叶角饰',
    themeColor: '#1c5b6b',
    settings: {
      designOn: true,
      print: 'photogravure',
      inkColor: '#1c5b6b',
      frameColor: '#1c5b6b',
      vignetteColor: '#1c5b6b',
      typeface: 'didone',
      frame: 'ornate',
      vignette: 'oval',
      vignetteRule: true,
      feather: 0.12,
      ornament: 'leaf',
      ornamentSize: 0.09,
      country: 'WILDLIFE PROTECTION',
      denomination: '29',
      denomAnchor: 'bottom-center',
      tablets: false,
      caption: '',
      ribbon: false,
      ground: 'burelage',
      groundColor: '#1c5b6b',
      groundWeight: 0.3,
      groundScale: 0.22,
      groundStrength: 0.35,
      margin: 0.055,
      gauge: 12,
      toning: 0.18,
      edge: 'perforated',
    },
  },
  {
    id: 'maritime',
    label: 'Maritime 远洋巨帆',
    description: '深靛海蓝古典雕版 · 卷草角饰与双角反白面额座',
    themeColor: '#1b3350',
    settings: {
      designOn: true,
      print: 'engraved',
      inkColor: '#1b3350',
      frameColor: '#1b3350',
      vignetteColor: '#1b3350',
      typeface: 'serif',
      frame: 'ornate',
      vignette: 'arch',
      vignetteRule: true,
      ornament: 'scroll',
      ornamentSize: 0.08,
      countryArc: true,
      tablets: true,
      ribbon: true,
      country: 'MARITIME HERITAGE',
      denomination: '50',
      caption: 'AT SEA 扬帆起航',
      margin: 0.05,
      gauge: 11,
      toning: 0.28,
      wear: 0.18,
      edge: 'perforated',
    },
  },
  {
    id: 'botanical',
    label: 'Botanical 经典花卉',
    description: '紫晶优雅柔调 · 交叉影线与四角罗盘玫瑰',
    themeColor: '#4f3068',
    settings: {
      designOn: true,
      print: 'photogravure',
      inkColor: '#4f3068',
      frameColor: '#4f3068',
      vignetteColor: '#4f3068',
      typeface: 'serif',
      frame: 'classic',
      vignette: 'oval',
      vignetteRule: true,
      feather: 0.08,
      ornament: 'rosette',
      ornamentSize: 0.09,
      country: 'BOTANICAL SPECIMEN',
      denomination: '8',
      tablets: false,
      caption: 'FLORA 珍稀花卉',
      ribbon: true,
      ground: 'crosshatch',
      groundColor: '#4f3068',
      groundWeight: 0.35,
      groundScale: 0.25,
      groundStrength: 0.38,
      margin: 0.055,
      gauge: 12,
      toning: 0.15,
      edge: 'perforated',
    },
  },
  {
    id: 'engineering',
    label: 'Engineering 工业大桥',
    description: '铁锈红棕时代印记 · 装饰派阶梯线条角饰',
    themeColor: '#7b3420',
    settings: {
      designOn: true,
      print: 'engraved',
      inkColor: '#7b3420',
      frameColor: '#7b3420',
      vignetteColor: '#7b3420',
      typeface: 'grotesque',
      frame: 'classic',
      vignette: 'rect',
      vignetteRule: true,
      ornament: 'deco',
      ornamentSize: 0.09,
      country: 'INDUSTRIAL ACHIEVEMENT',
      denomination: '60',
      caption: 'GRAND BRIDGE 宏伟铁桥',
      ribbon: false,
      tablets: true,
      margin: 0.05,
      gauge: 11.5,
      toning: 0.22,
      wear: 0.2,
      edge: 'perforated',
    },
  },
];
