"""Open Agent SDK for Python.

A complete, open-source Agent SDK that runs the full agent loop in-process.
Deploy anywhere: cloud, serverless, Docker, CI/CD.
"""

__version__ = "0.1.0"

# ─── High-Level API ──────────────────────────────────────────────────────────
from open_agent_sdk.agent import Agent, create_agent, query

# ─── Core Types ──────────────────────────────────────────────────────────────
from open_agent_sdk.types import (
    AgentDefinition,
    AgentOptions,
    AssistantMessage,
    BaseTool,
    CanUseToolFn,
    CanUseToolResult,
    ContentBlock,
    ContentBlockType,
    ConversationMessage,
    MCPConnection,
    McpHttpConfig,
    McpServerConfig,
    McpSseConfig,
    McpStdioConfig,
    MessageRole,
    PermissionBehavior,
    PermissionMode,
    QueryResult,
    SDKMessage,
    SDKMessageType,
    SDKResultStatus,
    SDKSystemSubtype,
    ThinkingConfig,
    TokenUsage,
    ToolContext,
    ToolDefinition,
    ToolInputSchema,
    ToolResult,
    UserMessage,
)

# ─── Engine ──────────────────────────────────────────────────────────────────
from open_agent_sdk.engine import QueryEngine, QueryEngineConfig


# ─── Providers ───────────────────────────────────────────────────────────
from open_agent_sdk.providers import (
    ApiType,
    CreateMessageParams,
    CreateMessageResponse,
    LLMProvider,
    NormalizedTool,
    AnthropicProvider,
    OpenAIProvider,
    create_provider,
)

# ─── Tool Helper ─────────────────────────────────────────────────────────────
from open_agent_sdk.tool_helper import (
    CallToolResult,
    PydanticTool,
    ToolAnnotations,
    define_tool,
    tool,
    tool_to_api_schema,
)

# ─── MCP ─────────────────────────────────────────────────────────────────────
from open_agent_sdk.mcp.client import connect_mcp_server, close_all_connections
from open_agent_sdk.sdk_mcp_server import (
    McpSdkServerConfig,
    create_sdk_mcp_server,
    is_sdk_server_config,
)

# ─── Tools ───────────────────────────────────────────────────────────────────
from open_agent_sdk.tools import (
    # Tool classes
    BashTool,
    FileReadTool,
    FileWriteTool,
    FileEditTool,
    GlobTool,
    GrepTool,
    NotebookEditTool,
    WebFetchTool,
    WebSearchTool,
    AgentTool,
    SendMessageTool,
    TaskCreateTool,
    TaskListTool,
    TaskUpdateTool,
    TaskGetTool,
    TaskStopTool,
    TaskOutputTool,
    TeamCreateTool,
    TeamDeleteTool,
    EnterWorktreeTool,
    ExitWorktreeTool,
    EnterPlanModeTool,
    ExitPlanModeTool,
    AskUserQuestionTool,
    ToolSearchTool,
    ListMcpResourcesTool,
    ReadMcpResourceTool,
    CronCreateTool,
    CronDeleteTool,
    CronListTool,
    RemoteTriggerTool,
    LSPTool,
    ConfigTool,
    TodoWriteTool,
    SkillTool,
    # Registry functions
    get_all_base_tools,
    filter_tools,
    assemble_tool_pool,
    # State management
    get_all_tasks,
    get_task,
    clear_tasks,
    get_all_teams,
    get_team,
    clear_teams,
    read_mailbox,
    write_to_mailbox,
    clear_mailboxes,
    is_plan_mode_active,
    get_current_plan,
    register_agents,
    clear_agents,
    set_question_handler,
    clear_question_handler,
    set_deferred_tools,
    set_mcp_connections,
    get_all_cron_jobs,
    clear_cron_jobs,
    get_config,
    set_config,
    clear_config,
    get_todos,
    clear_todos,
)

# ─── Skills ──────────────────────────────────────────────────────────────────
from open_agent_sdk.skills import (
    SkillContentBlock,
    SkillDefinition,
    SkillResult,
    register_skill,
    get_skill,
    get_all_skills,
    get_user_invocable_skills,
    has_skill,
    unregister_skill,
    clear_skills,
    format_skills_for_prompt,
    init_bundled_skills,
)

# ─── Session ─────────────────────────────────────────────────────────────────
from open_agent_sdk.session import (
    append_to_session,
    delete_session,
    fork_session,
    get_session_info,
    get_session_messages,
    list_sessions,
    load_session,
    rename_session,
    save_session,
    tag_session,
)

# ─── Utilities ───────────────────────────────────────────────────────────────
from open_agent_sdk.utils import (
    # Messages
    create_user_message,
    create_assistant_message,
    normalize_messages_for_api,
    strip_images_from_messages,
    extract_text_from_content,
    create_compact_boundary_message,
    truncate_text,
    # Tokens & Cost
    estimate_tokens,
    estimate_messages_tokens,
    estimate_system_prompt_tokens,
    get_token_count_from_usage,
    get_context_window_size,
    get_auto_compact_threshold,
    estimate_cost,
    MODEL_PRICING,
    AUTOCOMPACT_BUFFER_TOKENS,
    # Compaction
    AutoCompactState,
    should_auto_compact,
    compact_conversation,
    micro_compact_messages,
    create_auto_compact_state,
    # Retry
    RetryConfig,
    DEFAULT_RETRY_CONFIG,
    with_retry,
    is_retryable_error,
    is_auth_error,
    is_rate_limit_error,
    is_prompt_too_long_error,
    format_api_error,
    get_retry_delay,
    # Context
    get_system_context,
    get_user_context,
    get_git_status,
    clear_context_cache,
    # File Cache
    FileState,
    FileStateCache,
    create_file_state_cache,
)

# ─── Hooks ───────────────────────────────────────────────────────────────────
from open_agent_sdk.hooks import (
    HookEvent,
    HookInput,
    HookOutput,
    HookDefinition,
    HookRegistry,
    create_hook_registry,
    HOOK_EVENTS,
)

__all__ = [
    # Version
    "__version__",
    # High-Level API
    "Agent",
    "create_agent",
    "query",
    # Engine
    "QueryEngine",
    "QueryEngineConfig",
    # Providers
    "ApiType",
    "CreateMessageParams",
    "CreateMessageResponse",
    "LLMProvider",
    "NormalizedTool",
    "AnthropicProvider",
    "OpenAIProvider",
    "create_provider",
    # Types
    "AgentDefinition",
    "AgentOptions",
    "AssistantMessage",
    "BaseTool",
    "CanUseToolFn",
    "CanUseToolResult",
    "ContentBlock",
    "ContentBlockType",
    "ConversationMessage",
    "MCPConnection",
    "McpHttpConfig",
    "McpServerConfig",
    "McpSseConfig",
    "McpStdioConfig",
    "MessageRole",
    "PermissionBehavior",
    "PermissionMode",
    "QueryResult",
    "SDKMessage",
    "SDKMessageType",
    "SDKResultStatus",
    "SDKSystemSubtype",
    "ThinkingConfig",
    "TokenUsage",
    "ToolContext",
    "ToolDefinition",
    "ToolInputSchema",
    "ToolResult",
    "UserMessage",
    # Tool Helper
    "CallToolResult",
    "PydanticTool",
    "ToolAnnotations",
    "define_tool",
    "tool",
    "tool_to_api_schema",
    # MCP
    "connect_mcp_server",
    "close_all_connections",
    "McpSdkServerConfig",
    "create_sdk_mcp_server",
    "is_sdk_server_config",
    # Tools
    "BashTool",
    "FileReadTool",
    "FileWriteTool",
    "FileEditTool",
    "GlobTool",
    "GrepTool",
    "NotebookEditTool",
    "WebFetchTool",
    "WebSearchTool",
    "AgentTool",
    "SendMessageTool",
    "TaskCreateTool",
    "TaskListTool",
    "TaskUpdateTool",
    "TaskGetTool",
    "TaskStopTool",
    "TaskOutputTool",
    "TeamCreateTool",
    "TeamDeleteTool",
    "EnterWorktreeTool",
    "ExitWorktreeTool",
    "EnterPlanModeTool",
    "ExitPlanModeTool",
    "AskUserQuestionTool",
    "ToolSearchTool",
    "ListMcpResourcesTool",
    "ReadMcpResourceTool",
    "CronCreateTool",
    "CronDeleteTool",
    "CronListTool",
    "RemoteTriggerTool",
    "LSPTool",
    "ConfigTool",
    "TodoWriteTool",
    "SkillTool",
    # Registry
    "get_all_base_tools",
    "filter_tools",
    "assemble_tool_pool",
    # State
    "get_all_tasks",
    "get_task",
    "clear_tasks",
    "get_all_teams",
    "get_team",
    "clear_teams",
    "read_mailbox",
    "write_to_mailbox",
    "clear_mailboxes",
    "is_plan_mode_active",
    "get_current_plan",
    "register_agents",
    "clear_agents",
    "set_question_handler",
    "clear_question_handler",
    "set_deferred_tools",
    "set_mcp_connections",
    "get_all_cron_jobs",
    "clear_cron_jobs",
    "get_config",
    "set_config",
    "clear_config",
    "get_todos",
    "clear_todos",
    # Session
    "save_session",
    "load_session",
    "list_sessions",
    "fork_session",
    "get_session_messages",
    "get_session_info",
    "rename_session",
    "tag_session",
    "append_to_session",
    "delete_session",
    # Utils
    "create_user_message",
    "create_assistant_message",
    "normalize_messages_for_api",
    "strip_images_from_messages",
    "extract_text_from_content",
    "create_compact_boundary_message",
    "truncate_text",
    "estimate_tokens",
    "estimate_messages_tokens",
    "estimate_system_prompt_tokens",
    "get_token_count_from_usage",
    "get_context_window_size",
    "get_auto_compact_threshold",
    "estimate_cost",
    "MODEL_PRICING",
    "AUTOCOMPACT_BUFFER_TOKENS",
    "AutoCompactState",
    "should_auto_compact",
    "compact_conversation",
    "micro_compact_messages",
    "create_auto_compact_state",
    "RetryConfig",
    "DEFAULT_RETRY_CONFIG",
    "with_retry",
    "is_retryable_error",
    "is_auth_error",
    "is_rate_limit_error",
    "is_prompt_too_long_error",
    "format_api_error",
    "get_retry_delay",
    "get_system_context",
    "get_user_context",
    "get_git_status",
    "clear_context_cache",
    "FileState",
    "FileStateCache",
    "create_file_state_cache",
    # Hooks
    "HookEvent",
    "HookInput",
    "HookOutput",
    "HookDefinition",
    "HookRegistry",
    "create_hook_registry",
    "HOOK_EVENTS",
    # Skills
    "SkillContentBlock",
    "SkillDefinition",
    "SkillResult",
    "register_skill",
    "get_skill",
    "get_all_skills",
    "get_user_invocable_skills",
    "has_skill",
    "unregister_skill",
    "clear_skills",
    "format_skills_for_prompt",
    "init_bundled_skills",
]
