/**
 * 杂志排版模块 - 6 款经典版面预设 (Presets)
 * 参考真实国际刊物版式设计（封面 Ribbon、焦点跨页特写、访谈金句、双图画廊、黑白反差块、极简文学）
 */

import type { EditorialPreset } from './types';

export const EDITORIAL_PRESETS: EditorialPreset[] = [
  {
    id: 'cover_ribbon',
    name: '封面先锋',
    englishName: 'Cover & Ribbon',
    description: '侧边黑色标签带 (ISSUE 08)、大字压图标题、底部条形码与期号',
    columns: 2,
    defaultRatio: '3:4',
    features: {
      hasRibbonTag: true,
      hasBarcode: true,
      headlinePlacement: 'overlap',
    },
    defaultArticle: {
      masthead: 'ECHOES FORGE CLAW · ISSUE 08',
      headline: 'MAGAZINE',
      deck: 'PROFESSIONAL MAGAZINE EDITORIAL SYSTEM FOR CREATIVE DESIGNS',
      author: 'ECHOES FORGE STUDIO',
      body: '现代排版设计的本质是构建清晰的视觉秩序与呼吸感。通过精确的网格系统、张弛有度的字符间距以及图文穿插的动态绕排，版面不再是静态的图文堆砌，而是一个充满节奏与韵律的视觉有机体。每一次文本的流动与避让，都在向读者传递着深邃而优雅的美学力量。',
      folio: 'VOL. 08 · NO. 2026',
      issueDate: '01 - 07 - 2026',
    },
    defaultTypography: {
      headlineFont: 'MiSans, "Helvetica Neue", sans-serif',
      bodyFont: 'MiSans, "Helvetica Neue", sans-serif',
      textColor: '#1a1a1a',
      accentColor: '#000000',
      bodyFontSize: 20,
      bodyLineHeight: 32,
      dropCap: true,
      dropCapLines: 3,
      colGap: 40,
    },
    defaultBackground: {
      type: 'color',
      color: '#f8f8f6',
    },
  },
  {
    id: 'feature_spread',
    name: '跨页特写',
    englishName: 'Feature Story',
    description: '顶部/左侧大面积焦点图，醒目粗黑主标题，正文 2 栏连续流动',
    columns: 2,
    defaultRatio: '16:9',
    features: {
      hasRibbonTag: false,
      hasBarcode: false,
      headlinePlacement: 'top',
    },
    defaultArticle: {
      masthead: 'FEATURE STORY · SPECIAL REPORT',
      headline: 'THE FUTURE OF CREATIVE DESIGN',
      deck: 'How dynamic text reflow and algorithmic typography are redefining modern editorial experiences.',
      author: 'BY LEOPOLD ASCHENBRENNER & ECHOES FORGE',
      body: '在数字时代，刊物排版正经历着从静态文档向交互式流体布局的深刻变革。Pretext 引擎通过纯数学算术完成了文本分词与测量，彻底摆脱了传统 DOM 测量的性能枷锁。无论是多栏跨页接力、还是多边形障碍物避让，排版引擎都能在毫秒之内完成重排，使高阶杂志排版能够像水流般在任意几何形状之间无缝流动。',
      folio: 'PAGE 05 · ECHOES FORGE ESSAY',
      issueDate: '2026.08',
    },
    defaultTypography: {
      headlineFont: '"Iowan Old Style", "Noto Serif SC", serif',
      bodyFont: '"Noto Serif SC", "Iowan Old Style", serif',
      textColor: '#222222',
      accentColor: '#8b261e',
      bodyFontSize: 22,
      bodyLineHeight: 36,
      dropCap: true,
      dropCapLines: 3,
      colGap: 48,
    },
    defaultBackground: {
      type: 'color',
      color: '#ffffff',
    },
  },
  {
    id: 'quote_interview',
    name: '访谈金句',
    englishName: 'Interview & Quote',
    description: '醒目大字引语、带引号观点卡片、3 栏文本穿插环绕避让',
    columns: 3,
    defaultRatio: '3:4',
    features: {
      hasRibbonTag: false,
      hasBarcode: false,
      headlinePlacement: 'top',
      pullquotePlacement: 'card',
    },
    defaultArticle: {
      masthead: 'INTERVIEW · PERSPECTIVES',
      headline: 'LET’S DO WHAT YOU WANT TO DO.',
      deck: 'An in-depth conversation on craftsmanship, aesthetics, and artificial intelligence.',
      author: 'INTERVIEWED BY DESIGN TEAM',
      pullquote: '“真正卓越的排版不是喧宾夺主，而是让内容在最适宜的光线与空间中自然呼吸。”',
      body: '当我们谈论版面美学时，不仅是在讨论字体的选择或图片的大小，更是在探讨视觉注意力的流动轨迹。从文艺复兴时期的古腾堡圣经，到现代瑞士国际主义网格系统，排版始终在严谨的数学比例与感性的艺术直觉之间寻找平衡。当 AI 与智能排版结合，设计师得以从繁重的体力调校中解脱，专注于更高维度的构思与意境表达。',
      folio: 'PERSPECTIVES · 09',
      issueDate: 'SUMMER 2026',
    },
    defaultTypography: {
      headlineFont: 'MiSans, "Helvetica Neue", sans-serif',
      bodyFont: '"Huiwen-mincho", "Noto Serif SC", serif',
      textColor: '#1f1e1c',
      accentColor: '#c85554',
      bodyFontSize: 19,
      bodyLineHeight: 31,
      dropCap: false,
      colGap: 32,
    },
    defaultBackground: {
      type: 'color',
      color: '#faf9f5',
    },
  },
  {
    id: 'gallery_duo',
    name: '双图画廊',
    englishName: 'Gallery & Duo',
    description: '左右错落双图、正文在图片空隙间自适应穿插流动、带图注',
    columns: 2,
    defaultRatio: '4:5',
    features: {
      hasRibbonTag: false,
      hasBarcode: false,
      headlinePlacement: 'top',
    },
    defaultArticle: {
      masthead: 'PHOTOGRAPHY & MEMORIES',
      headline: 'MOMENTS IN MOTION',
      deck: 'A visual journey through landscapes, architecture, and timeless human stories.',
      author: 'CURATED BY ECHOES FORGE',
      body: '光影记录了时间的厚度，而排版则为这些瞬间提供了安静驻足的容器。在双图交错的画廊版面中，文字不再是呆板的说明，而是与图像产生对话的旋律。文字流随着图片的边缘自然折转，让整张画报呈现出如流水般的舒展与从容。',
      folio: 'GALLERY COLLECTION · 12',
      issueDate: 'ISSUE 04',
    },
    defaultTypography: {
      headlineFont: '"上图东观体", "Noto Serif SC", serif',
      bodyFont: '"上图东观体", "Noto Serif SC", serif',
      textColor: '#2d2a24',
      accentColor: '#3b5998',
      bodyFontSize: 21,
      bodyLineHeight: 34,
      dropCap: true,
      dropCapLines: 2,
      colGap: 36,
    },
    defaultBackground: {
      type: 'color',
      color: '#f6f5f0',
    },
  },
  {
    id: 'inverted_contrast',
    name: '黑白反色',
    englishName: 'Inverted Contrast',
    description: '左侧黑色高反差实心卡片、右侧多栏白底正文、垂直先锋标题条',
    columns: 2,
    defaultRatio: '3:4',
    features: {
      hasRibbonTag: true,
      hasBarcode: true,
      hasInvertedBlock: true,
      headlinePlacement: 'left-col',
    },
    defaultArticle: {
      masthead: 'BRUTALISM & ARCHITECTURE',
      headline: 'CREATIVE MIND',
      deck: 'Exploring the raw power of high contrast and radical typography.',
      author: 'STUDIO ESSAY',
      body: '高对比度的黑白反色是粗野主义与先锋平面设计的标志性语言。黑色色块的沉重感与大面积留白的轻盈感产生强烈戏剧张力。在这种版面结构中，信息被赋予了前所未有的力量与现代感，每一个字符都在黑白两极之间彰显出冷峻而坚定的态度。',
      folio: 'ARCHITECTURE NO. 07',
      issueDate: '2026.08',
    },
    defaultTypography: {
      headlineFont: 'MiSans, "Helvetica Neue", sans-serif',
      bodyFont: 'MiSans, "Helvetica Neue", sans-serif',
      textColor: '#111111',
      accentColor: '#000000',
      bodyFontSize: 20,
      bodyLineHeight: 32,
      dropCap: false,
      colGap: 36,
    },
    defaultBackground: {
      type: 'color',
      color: '#ffffff',
    },
  },
  {
    id: 'minimal_editorial',
    name: '极简文学',
    englishName: 'Minimal Editorial',
    description: 'Kinfolk 式大留白、不对称双栏、细线分割、古典明朝体正文',
    columns: 2,
    defaultRatio: '3:4',
    features: {
      hasRibbonTag: false,
      hasBarcode: false,
      headlinePlacement: 'top',
    },
    defaultArticle: {
      masthead: 'LITERATURE & ESSAY',
      headline: 'THE ART OF QUIET LIVING',
      deck: 'Reflections on solitude, nature, and the subtle beauty of everyday objects.',
      author: 'WRITTEN BY ANONYMOUS',
      body: '生活需要适度的空白，如同版面需要留白一样。当过多的杂音被剔除，留下的才是思想最真实的质感。明朝体的横细竖粗在淡米色的纸张上沉静舒展，仿佛一盏温润的茶，让阅读重新回归纯粹与沉静。',
      folio: 'LITERATURE · VOL 01',
      issueDate: '2026',
    },
    defaultTypography: {
      headlineFont: '"Huiwen-mincho", "又又意宋", serif',
      bodyFont: '"Huiwen-mincho", "又又意宋", serif',
      textColor: '#33302a',
      accentColor: '#8b5e3c',
      bodyFontSize: 21,
      bodyLineHeight: 35,
      dropCap: true,
      dropCapLines: 3,
      colGap: 44,
    },
    defaultBackground: {
      type: 'color',
      color: '#fcfbfa',
    },
  },
];

export const DEFAULT_EDITORIAL_PRESET = EDITORIAL_PRESETS[0];

export function getEditorialPreset(id: string): EditorialPreset {
  return EDITORIAL_PRESETS.find((p) => p.id === id) || DEFAULT_EDITORIAL_PRESET;
}
