"""add updated_at columns

Revision ID: 807a1012196f
Revises: 5500564c2ee7
Create Date: 2026-08-08 15:21:56.287920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807a1012196f'
down_revision: Union[str, Sequence[str], None] = '5500564c2ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('prompt_templates', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('stage_configs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    # 历史数据回填：updated_at 取 created_at，保证必填字段有值
    op.execute("UPDATE llm_configs SET updated_at = created_at WHERE updated_at IS NULL")
    op.execute("UPDATE prompt_templates SET updated_at = created_at WHERE updated_at IS NULL")
    op.execute("UPDATE stage_configs SET updated_at = created_at WHERE updated_at IS NULL")
    op.execute("UPDATE users SET updated_at = created_at WHERE updated_at IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('stage_configs', 'updated_at')
    op.drop_column('prompt_templates', 'updated_at')
    op.drop_column('llm_configs', 'updated_at')
    # ### end Alembic commands ###
