import type { VoiceDictationOutputContext } from '../../types'

/**
 * Keeps a dictation session's output choice stable while recognition is in flight.
 * A context ID is generated by the main process and echoed by the renderer on preview,
 * commit, and cancel IPC calls, so changing settings mid-session cannot reroute text.
 */
export class VoiceDictationOutputContextStore {
  private readonly contexts = new Map<string, VoiceDictationOutputContext>()

  begin(contextId: string, context: VoiceDictationOutputContext): void {
    this.contexts.set(contextId, { ...context })
  }

  get(contextId?: string): VoiceDictationOutputContext | undefined {
    return contextId ? this.contexts.get(contextId) : undefined
  }

  release(contextId?: string): void {
    if (contextId) this.contexts.delete(contextId)
  }
}
