# This is a config for E2B sandbox template.
# You can use template ID (95m23hiiqsx9u65ayuvo) or template name (fastclaw-sandbox) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("fastclaw-sandbox") # Sync sandbox
# sandbox = await AsyncSandbox.create("fastclaw-sandbox") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('fastclaw-sandbox')

start_cmd = "sleep infinity"
dockerfile = "e2b.Dockerfile"
template_name = "fastclaw-sandbox"
template_id = "95m23hiiqsx9u65ayuvo"
